### ISSUE TITLE
logback implementation forced on users

### ISSUE THREAD

**Issue by aryaKetan** [regunathb/Trooper#39]
Can we in trooper log to logging interface slf4j and let consumers decide whether they want logback or log4j2.

**Comment by regunathb** [comment]
A valid issue. Is there a need for users to have the logging config file in a location other than classpath? Ideally, the logging file should not be included in archives like .jar files along with the compiled binaries. If that is an acceptable stance, where should the config files be deployed and how will they be configured during startup?

**Comment by aryaKetan** [comment]
its not about the logging config file location.. right now.. logback logging implementation is forced on users. I may want to use log4j or log4j2 implementations. so ..

**Comment by regunathb** [comment]
This is now implemented. Trooper basic runtime only depends on slf4j logging facade. Specific component container implementations - e.g. Batch, SEDA or any custom ones provide their own slf4j logging binding such as slf4j over log4j, if log4j is the logging library as the case may be.
Available in release version 2.0.0.
